jwt:
  secretKey: ahgoewwjohov0330&@)*_099ruejl0asghoiwjodnva;huii5rti0u09908


spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
#            - name: Authentication
              args:
                isEnable: true

        #            - RedirectTo=302, http://codingshuttle.com



        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Ashish
            - name: Authentication
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
