spring.application.name: config-server
spring:
  cloud:
    config:
      server:
        get:
          uri: https://github.com/ashipatel0856/microService.git
          username: ashipatel0856
          password:
          default-label: master
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



